spring:
  application:
    name: sites-service
resilience4j:
  circuitbreaker:
    instances:
      firestoreCb:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true