substitutions:
  _IMAGE_NAME: "sites-service"
  _INFRA_REPO_URL: "https://github.com/green-energy-tracker-cloud/infra.git"
  _CLOUDBUILD_CONFIG_PATH: "cloudbuild/cloudbuild.yaml"

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'builds', 'submit',
        '--config', '$_CLOUDBUILD_CONFIG_PATH',
        '--substitutions=_IMAGE_NAME=_IMAGE_NAME,_VERSION=$_VERSION',
        '$_INFRA_REPO_URL'
      ]