substitutions:
  _ARTIFACT_REGISTRY_REPO: "green-energy-tracker-cloud-repo"
  _IMAGE_NAME: "sites-service"
  _LOCATION: "europe-west8"

steps:

  - name: 'gcr.io/cloud-builders/mvn'
    args: [ 'clean', 'package' ]

  - name: 'gcr.io/cloud-builders/mvn'
    args: [
      'com.google.cloud.tools:jib-maven-plugin:3.4.5:build',
      '-Dimage=$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_IMAGE_NAME:$COMMIT_SHA'
    ]

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
